config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: %i[confirmation unlock passwords]
  root to: 'blog/home#index'
  resources :articles, only: %i[index show],
                       controller: 'blog/articles',
                       param: 'slug'
  devise_scope :user do
    namespace :admin do
      root to: 'dashboard#index'
      resources :articles, param: 'slug'
      resources :users
    end
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.administrator?
      can :manage, :all
    else
      can :manage, Article, author_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id               :bigint           not null, primary key
#  title            :string
#  slug             :string
#  meta_keywords    :string
#  meta_description :text
#  content          :text
#  published        :boolean
#  author_id        :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Article < ApplicationRecord
  extend FriendlyId

  friendly_id :title

  belongs_to :author, class_name: 'User', inverse_of: :articles

  delegate :email, to: :author, prefix: true

  default_scope { eager_load(:author) }

  scope :published, -> { where(published: true) }

  scope :recent, ->{ order(created_at: :desc) }

  validates :title, presence: true, length: { minimum: 3 }

  validates :content, presence: true, length: { minimum: 100 }

  def self.permitted_attributes
    [
      :title,
      :content,
      :meta_keywords,
      :meta_description,
      :published
    ]
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :bigint           not null, primary key
#  email               :string           default(""), not null
#  encrypted_password  :string           default(""), not null
#  remember_created_at :datetime
#  sign_in_count       :integer          default(0), not null
#  current_sign_in_at  :datetime
#  last_sign_in_at     :datetime
#  current_sign_in_ip  :string
#  last_sign_in_ip     :string
#  role                :string           default("regular_user")
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#
class User < ApplicationRecord
  ROLES = {
    regular_user: 'regular_user',
    administrator: 'administrator'
  }.freeze

  devise :database_authenticatable,
         :registerable,
         :rememberable,
         :validatable,
         :trackable

  enum role: ROLES

  with_options foreign_key: 'author_id' do
    has_many :articles, dependent: :destroy, inverse_of: :author
    has_many :published_articles, -> { published }, class_name: 'Article'
  end

  before_validation :ensure_role, on: :create

  private

  def ensure_role
    self.role = ROLES[:regular_user] unless role
  end
end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < BaseController
    load_and_authorize_resource

    before_action :find_article, except: %i[index new create]

    def index
      @articles = load_articles.recent
    end

    def new
      @article = current_user.articles.new
    end

    def create
      @article = current_user.articles.new(article_params)

      if @article.save
        flash[:notice] = 'Article posted'
        redirect_to admin_articles_path
      else
        flash[:error] = @article.errors.full_messages.first
        render :new
      end
    end

    def show; end

    def edit; end

    def update
      if @article.update(article_params)
        flash[:notice] = 'Article updated'
        redirect_to admin_article_path(slug: @article.slug)
      else
        flash[:error] = @article.errors.full_messages.first
        render :edit
      end
    end

    def destroy
      if @article.destroy
        flash[:notice] = 'Article deleted'
      else
        flash[:error] = @article.errors.full_messages.first
      end

      redirect_to admin_articles_path
    end

    private

    def load_articles
      collection = if current_user.administrator?
                     Article.includes(:author)
                   else
                     current_user.articles
                   end

      collection
    end

    def article_params
      params.require(:article).permit(*Article.permitted_attributes)
    end

    def find_article
      @article = load_articles.where(articles: { slug: params[:slug] }).first
    end
  end
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
    layout 'admin'
  end
end

app/controllers/admin/dashboard_controller.rb
module Admin
  class DashboardController < BaseController
    def index
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < BaseController
    load_and_authorize_resource

    before_action :find_user, except: %i[index new create]

    def index
      @users = User.all
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)

      if @user.save
        flash[:notice] = 'User created'
        redirect_to admin_users_path
      else
        flash[:error] = @user.errors.full_messages.first
        render :new
      end
    end

    def show; end

    def edit; end

    def update
      if @user.update(user_params)
        flash[:notice] = 'User updated'
        redirect_to admin_user_path(id: params[:id])
      else
        flash[:error] = @user.errors.full_messages.first
        render :edit
      end
    end

    def destroy
      if @user.destroy
        flash[:notice] = 'User deleted'
      else
        flash[:error] = @user.errors.full_messages.first
      end

      redirect_to admin_users_path
    end

    private

    def user_params
      params.require(:user).permit(User.permitted_attributes)
    end

    def find_user
      @user = User.find(params[:id])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/blog/articles_controller.rb
module Blog
  class ArticlesController < BaseController
    def index
      @previous_older_than = Time.zone.parse(params[:older_than]) rescue nil
      @articles = Article.published
                         .recent
                         .limit(10)
      if @previous_older_than
        @articles = @articles.where('articles.created_at < ?', @previous_older_than)
      end
      
      @next_older_than = @articles.last.try(:created_at)
    end

    def show
      @article = Article.friendly.find(params[:slug])
    end
  end
end

app/controllers/blog/base_controller.rb
module Blog
  class BaseController < ActionController::Base
    layout 'blog'
  end
end

app/controllers/blog/home_controller.rb
module Blog
  class HomeController < BaseController
    def index
      @articles = Article.published.recent.limit(5)
      @next_older_than = @articles.last.try(:created_at).presence || Time.zone.now
    end
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
  def bootstrap_alert(message, type = 'info')
    alert_class = case type
                  when 'notice'
                    'warning'
                  when /error|alert/
                    'danger'
                  else
                    'info'
                  end
    render partial: 'admin/shared/flash',
           locals: { type: type,
                     alert_class: alert_class,
                     message: message }
  end

  def flash_message(resource: nil)
    return nil if flash.empty? && !resource

    type, message = if flash.any?
                      flash.first
                    elsif resource.errors.any?
                      ['error', resource.errors.full_messages.first]
                    else
                      [nil, nil]
                    end
    return nil unless message

    bootstrap_alert(message, type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog/articles_helper.rb
module Blog::ArticlesHelper
  def articles_list
    render partial: 'blog/articles/list',
           locals: { articles: @articles,
                     newer_than: @previous_older_than,
                     older_than: @next_older_than }
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/articles/_form.html.erb
<%= flash_message(resource: form.object) %>

<div class="form-group">
  <%= form.label :title, class: 'small mb-1' %>
  <%= form.text_field :title, class: 'form-control py-4', placeholder: 'Title' %>
</div>
<div class="form-group">
  <%= form.label :content, class: 'small mb-1' %>
  <%= form.text_area :content, class: 'form-control py-4', placeholder: 'Content' %>
</div>
<div class="card mb-4">
  <div class="card-header">
    Meta Tags
  </div>
  <div class="card-body">
    <div class="form-group">
      <%= form.label :meta_keywords, class: 'small mb-1' %>
      <%= form.text_field :meta_keywords, class: 'form-control py-4', placeholder: 'blog, seo, keyword' %>
    </div>
    <div class="form-group">
      <%= form.label :meta_description, class: 'small mb-1' %>
      <%= form.text_area :meta_description, class: 'form-control py-4', placeholder: 'Description' %>
    </div>
  </div>
</div>
<div class="d-flex align-items-center justify-content-between">
  <div class="form-group">
    <div class="form-check">
      <%= form.check_box :published, class: 'form-check-input' %>
      <%= form.label :published, class: 'form-check-label' %>
    </div>
  </div>
  <div class="form-group">
    <%= link_to('Discard and back to list', admin_articles_path, class: 'btn btn-link') %>
    <%= form.submit class: 'btn btn-primary' %>
  </div>
</div>

app/views/admin/articles/edit.html.erb
<% content_for :heading, @article.title %>
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item">
    <%= link_to('Articles', admin_articles_path) %>
  </li>
  <li class="breadcrumb-item">
    <%= link_to(@article.id, admin_article_path(slug: @article.slug)) %>
  </li>
  <li class="breadcrumb-item">Edit</li>
<% end %>

<%= form_with model: [:admin, @article], method: :put do |form| %>
  <%= render partial: 'admin/articles/form', locals: { form: form } %>
<% end %>

app/views/admin/articles/index.html.erb
<% content_for :heading, 'Articles' %>
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item">Articles</li>
<% end %>
<div class="d-flex justify-content-end mb-4">
  <%= link_to(new_admin_article_path, class: 'btn btn-primary') do %>
    <i class="fas fa-plus"></i> Create Article
  <% end %>
</div>
<div class="card mb-4">
  <div class="card-header">
    <i class="fas fa-table mr-1"></i>
    List of Articles
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Posted at</th>
            <th>Published</th>
            <th></th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Posted at</th>
            <th>Published</th>
            <th></th>
          </tr>
        </tfoot>
        <tbody>
          <% if @articles.empty? %>
          <tr>
            <td colspan="5"><em>No record found</em></td>
          </tr>
          <% end %>
          <% @articles.each do |article| %>
          <tr>
            <td><strong><%= article.title %></strong></td>
            <td><%= article.author_email %></td>
            <td><%= l(article.created_at, format: :short) %></td>
            <td>
              <%= content_tag(:i, '', class: "fas fa-#{article.published? ? 'check' : 'times'}") %>
            </td>
            <td>
              <div class="d-flex justify-content-around align-items-center">
                <%= link_to(admin_article_path(slug: article.slug)) do %>
                  <i class="fas fa-info"></i>
                <% end %>
                <%= link_to(edit_admin_article_path(slug: article.slug)) do %>
                  <i class="fas fa-edit"></i>
                <% end %>
                <%= link_to(admin_article_path(slug: article.slug),
                            class: 'text-danger',
                            data: { remote: true,
                                    method: :delete,
                                    confirm: 'Are you sure?' }) do %>
                  <i class="fas fa-trash"></i>
                <% end %>
              </div>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/articles/new.html.erb
<% content_for :heading, 'New Article' %>
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item">
    <%= link_to('Articles', admin_articles_path) %>
  </li>
  <li class="breadcrumb-item">New</li>
<% end %>

<%= form_with model: [:admin, @article], method: :post do |form| %>
  <%= render partial: 'admin/articles/form', locals: { form: form } %>
<% end %>

app/views/admin/articles/show.html.erb
<% content_for :heading, @article.title %>
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item">
    <%= link_to('Articles', admin_articles_path) %>
  </li>
  <li class="breadcrumb-item"><%= @article.id %></li>
<% end %>
<div class="d-flex justify-content-start mb-4">
  <%= link_to(edit_admin_article_path(slug: @article.slug), class: 'btn btn-link btn-sm') do %>
    <i class="fas fa-edit"></i> Edit Article
  <% end %>
</div>
<dl class="row">
  <dt class="col-md-12">Title</dt>
  <dd class="col-md-12">
    <span>
      <%= @article.title %>
    </span>
    <%= content_tag(:i,
                    '',
                    class: "fas fa-#{@article.published? ? 'check text-success' : 'close text-danger'}",
                    title: @article.published? ? 'Published' : 'Not Published') %>
  </dd>
  <dt class="col-md-12">Content</dt>
  <dd class="col-md-12"><%= @article.content %></dd>
  <dt class="col-md-12">Meta Tags</dt>
  <dd class="col-md-12">
    <dl class="row">
      <dt class="col-md-2">
        <span class="small">Keywords</span>
      </dt>
      <dd class="col-md-10"><em><%= @article.meta_keywords.presence || '-' %></em></dd>
      <dt class="col-md-2">
        <span class="small">Description</span>
      </dt>
      <dd class="col-md-10"><em><%= @article.meta_description.presence || '-' %></em></dd>
    </dl>
  </dd>
</dl>

app/views/admin/dashboard/index.html.erb
<% content_for :heading, 'Dashboard' %>

app/views/admin/shared/_flash.html.erb
<%= content_tag(:div, class: "alert alert-dismissible alert-#{alert_class}",
                      role: 'alert') do %>
  <strong><%= t(type.to_sym, scope: %i[alerts title]) %></strong>
  <span><%= message.html_safe %></span>
<% end %>

app/views/admin/users/index.html.erb
<% content_for :heading, 'Users' %>
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item">Users</li>
<% end %>

<div class="card mb-4">
  <div class="card-header">
    <i class="fas fa-table mr-1"></i>
    List of Users
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Email</th>
            <th>Last Signed In</th>
            <th></th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th>Email</th>
            <th>Last Signed In</th>
            <th></th>
          </tr>
        </tfoot>
        <tbody>
          <% if @users.empty? %>
          <tr>
            <td colspan="5"><em>No record found</em></td>
          </tr>
          <% end %>
          <% @users.each do |user| %>
          <tr>
            <td><%= user.email %></td>
            <td><%= user.last_sign_in_at ? l(user.last_sign_in_at, format: :short) : '-' %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/blog/articles/_list.html.erb
<%= render partial: 'blog/articles/preview', collection: articles, as: :article %>

<hr />
<div class="clearfix">
  <%- if newer_than -%>
  <%= link_to(articles_path(newer_than: newer_than.to_s), class: 'btn btn-primary float-left') do %>
    Newer Posts &laquo;
  <% end %>
  <%- end -%>

  <%- if older_than -%>
  <%= link_to(articles_path(older_than: older_than.to_s), class: 'btn btn-primary float-right') do %>
    Older Posts &raquo;
  <% end %>
  <%- end -%>
</div>

app/views/blog/articles/_preview.html.erb
<div class="post-preview">
  <%= link_to(article_path(slug: article.slug)) do %>
    <h2 class="post-title"><%= article.title %></h2>
    <h3 class="post-subtitle"><%= article.meta_description %></h3>
  <% end %>
  <p class="post-meta">
    Posted by
    <a href="#!"><%= article.author_email %></a>
    on <%= l(article.created_at, format: :short) %>
  </p>
</div>

app/views/blog/articles/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <%= articles_list %>
    </div>
  </div>
</div>
<hr />

app/views/blog/articles/show.html.erb
<header class="masthead" style="background-image: url('<%= image_path('post-bg.jpg') %>')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-heading">
          <h1><%= @article.title %></h1>
          <h2 class="subheading"><%= @article.meta_description %></h2>
          <span class="meta">
            Posted by
            <a href="#!"><%= @article.author_email %></a>
            on <%= l(@article.created_at, format: :short) %>
          </span>
        </div>
      </div>
    </div>
  </div>
</header>

<article>
  <div class="container">
      <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <%= @article.content %>
          </div>
      </div>
  </div>
</article>

<hr />

app/views/blog/home/index.html.erb
<header class="masthead" style="background-image: url('<%= image_path('home-bg.jpg') %>');">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Clean Blog</h1>
          <span class="subheading">A Blog Theme by Start Bootstrap</span>
        </div>
      </div>
    </div>
  </div>
</header>

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <%= articles_list %>
    </div>
  </div>
</div>
<hr />

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Start Bootstrap - Admin</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="robots" content="noindex,nofollow" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'admin/base', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'admin/base', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
      <%= link_to('Start Bootstrap', admin_root_path, class: 'navbar-brand') %>
      <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item<%= current_page?('/admin') ? ' active': '' %>">
          <%= link_to('Dashboard', admin_root_path, class: 'nav-link') %>
        </li>
        <li class="nav-item">
          <%= link_to('Blog', root_path, class: 'nav-link',target: :blank) %>
        </li>
        <li class="nav-item">
          <%= link_to('Sign Out', destroy_user_session_path, class: 'nav-link btn btn-danger') %>
        </li>
      </ul>
    </nav>

    <div id="layoutSidenav">
      <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
          <div class="sb-sidenav-menu">
            <div class="nav">
              <%= link_to(admin_articles_path, class: "nav-link#{current_page?('/admin/articles') ? ' active': ''}") do %>
                <div class="sb-nav-link-icon">
                  <i class="fas fa-file"></i>
                </div>
                Articles
              <% end %>
              <%- if can? :manage, User -%>
              <%= link_to(admin_users_path, class: "nav-link#{current_page?('/admin/users') ? ' active': ''}") do %>
                <div class="sb-nav-link-icon">
                  <i class="fas fa-users"></i>
                </div>
                Users
              <% end %>
              <%- end -%>
            </div>
          </div>
          <div class="sb-sidenav-footer">
            <div class="small">Logged in as:</div>
            <%= current_user.email %>
          </div>
        </nav>
      </div>

      <div id="layoutSidenav_content">
        <main>
          <div class="container-fluid">
            <h1 class="mt-4"><%= yield :heading %></h1>
            <ol class="breadcrumb mb-4">
              <li class="breadcrumb-item">
                <% if current_page?('/admin') %>
                Dashboard
                <% else %>
                <%= link_to('Dashboard', admin_root_path) %>
                <% end %>
              </li>
              <%= yield :breadcrumb %>
            </ol>
            <%= yield %>
          </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
          <div class="container-fluid">
            <div class="d-flex align-items-center justify-content-between small">
              <div class="text-muted">Copyright &copy; Start Bootstrap 2021</div>
            </div>
          </div>
        </footer>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Start Bootstrap</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Start Bootstrap - Clean Blog</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <%= link_to('Start Bootstrap', root_path, class: 'navbar-brand') %>
        <button class="navbar-toggler navbar-toggler-right"
                type="button"
                data-toggle="collapse"
                data-target="#navbarResponsive"
                aria-controls="navbarResponsive"
                aria-expanded="false"
                aria-label="Toggle navigation">
            Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to("Articles", articles_path, class: 'nav-link') %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <span class="small">
                  <%= link_to('Sign Up', new_user_registration_path, class: 'text-info') %>
                </span>
                <span class="small mr-1 ml-1">or</span>
                <span class="small">
                  <%= link_to('Sign In', new_user_session_path, class: 'text-info') %>
                  if you're already a member?
                </span>
              </li>
            </ul>
            <p class="copyright text-muted">
              Copyright &copy; <%= link_to('Start Bootstrap', root_path) %> 2021
            </p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>